#username : who is the sender
#password : senders generated password from senders google account -> securtiy -> two step verification -> app password
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: xyz@gamil.com
    password: ujiolmjhtwedoopl
    
#  servlet:  
#    multipart:
#      enabled: true
#      max-request-size: 10MB
#      max-file-size: 10MB
